FROM ndslabs/novnc-base:1.0

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev build-essential && \
	pip install --upgrade pip 

RUN cd / && \
   wget -q http://download.jetbrains.com/python/pycharm-community-2016.2.tar.gz && \
   tar xvfz pycharm-community-2016.2.tar.gz &&  \
   rm pycharm-community-2016.2.tar.gz

ADD init.sh /init.sh
RUN chmod +x /init.sh

EXPOSE 80

CMD ["/init.sh"]

